# **TFModisco Downstream Analysis**

## **Single file**

In [5]:
# Load libraries
import h5py
import numpy as np
import pandas as pd
import os

import sys
#!{sys.executable} -m pip install lxml

In [6]:
# Paths

Lactotrophs_modisco="/scratch/prj/stem_cells_pituitary/Georgia/ChromBPnet/outputs/Lactotrophs/tf_modisco/modisco_results.h5"
motifs_results="/scratch/prj/stem_cells_pituitary/Georgia/ChromBPnet/outputs/Lactotrophs/tf_modisco/modisco_report/motifs.html"

In [5]:
# Reading the h5 results file

with h5py.File(Lactotrophs_modisco, 'r') as file:
    print("Keys: %s" % list(file.keys()))
    
    for key in file.keys():
        print(f"Inspecting group: {key}")
    print(file[key])

Keys: ['neg_patterns', 'pos_patterns']
Inspecting group: neg_patterns
Inspecting group: pos_patterns
<HDF5 group "/pos_patterns" (37 members)>

In [10]:
# Look into the pos_patterns 

with h5py.File(Lactotrophs_modisco, 'r') as file:
    # 1. See top level
    print("Top level:", list(file.keys()))
    
    # 2. Pick a group and see what's inside
    group_name = 'pos_patterns'
    print(f"Inside {group_name}:", list(file[group_name].keys()))
    
    # 3. Pick a specific pattern and see its datasets
    pattern_name = 'pattern_0'
    print(f"Inside {pattern_name}:", list(file[group_name][pattern_name].keys()))

Top level: ['neg_patterns', 'pos_patterns']
Inside pos_patterns: ['pattern_0', 'pattern_1', 'pattern_10', 'pattern_11', 'pattern_12', 'pattern_13', 'pattern_14', 'pattern_15', 'pattern_16', 'pattern_17', 'pattern_18', 'pattern_19', 'pattern_2', 'pattern_20', 'pattern_21', 'pattern_22', 'pattern_23', 'pattern_24', 'pattern_25', 'pattern_26', 'pattern_27', 'pattern_28', 'pattern_29', 'pattern_3', 'pattern_30', 'pattern_31', 'pattern_32', 'pattern_33', 'pattern_34', 'pattern_35', 'pattern_36', 'pattern_4', 'pattern_5', 'pattern_6', 'pattern_7', 'pattern_8', 'pattern_9']
Inside pattern_0: ['contrib_scores', 'hypothetical_contribs', 'seqlets', 'sequence', 'subpattern_0', 'subpattern_1', 'subpattern_2', 'subpattern_3', 'subpattern_4', 'subpattern_5', 'subpattern_6', 'subpattern_7', 'subpattern_8']

In [18]:
# Inspect the file and identify information

with h5py.File(Lactotrophs_modisco, 'r') as file:
    pos_patterns = file['pos_patterns']
    
    # Look at the first 5 motifs
    for motif in range(5):
        pattern_name = f'pattern_{motif}'
        if pattern_name in pos_patterns:
            group = pos_patterns[pattern_name]
            
            contrib_scores = group['contrib_scores'][:]
            sequence = group['sequence'][:]
            
            print(f"--- {pattern_name} ---")
            print(f"Sequence Shape: {sequence.shape}")
            print(f"Contribution Scores Shape: {contrib_scores.shape}")

--- pattern_0 ---
Sequence Shape: (30, 4)
Contribution Scores Shape: (30, 4)
--- pattern_1 ---
Sequence Shape: (30, 4)
Contribution Scores Shape: (30, 4)
--- pattern_2 ---
Sequence Shape: (30, 4)
Contribution Scores Shape: (30, 4)
--- pattern_3 ---
Sequence Shape: (30, 4)
Contribution Scores Shape: (30, 4)
--- pattern_4 ---
Sequence Shape: (30, 4)
Contribution Scores Shape: (30, 4)

In [7]:
# Look at the motifs.html file

table = pd.read_html(motifs_results)
df = table[0]
df

,pattern,num_seqlets,modisco_cwm_fwd,modisco_cwm_rev,match0,qval0,match0_logo,match1,qval1,match1_logo,match2,qval2,match2_logo
0,pos_patterns.pattern_0,3711,NaN,NaN,MA0139.2,1.486780e-15,NaN,MA1930.2,1.486780e-15,NaN,MA1930.1,1.486780e-15,NaN
1,pos_patterns.pattern_1,3540,NaN,NaN,MA0790.1,4.218360e-01,NaN,MA0791.1,4.218360e-01,NaN,MA0683.1,4.558050e-01,NaN
2,pos_patterns.pattern_2,2940,NaN,NaN,MA0835.3,3.074210e-03,NaN,MA1988.2,3.074210e-03,NaN,MA2486.1,3.074210e-03,NaN
3,pos_patterns.pattern_3,2468,NaN,NaN,MA0790.1,2.811640e-03,NaN,MA0791.1,2.884580e-03,NaN,MA0791.2,5.652540e-03,NaN
4,pos_patterns.pattern_4,2389,NaN,NaN,MA1467.2,1.834790e-05,NaN,MA1642.1,9.611720e-05,NaN,MA1109.1,1.429630e-04,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,neg_patterns.pattern_33,116,NaN,NaN,MA1499.2,3.040170e-01,NaN,MA1639.2,3.040170e-01,NaN,MA1504.2,3.040170e-01,NaN
71,neg_patterns.pattern_34,81,NaN,NaN,MA1596.1,8.553260e-02,NaN,MA0496.4,8.553260e-02,NaN,MA2587.1,8.553260e-02,NaN
72,neg_patterns.pattern_35,71,NaN,NaN,MA1124.1,6.074760e-01,NaN,MA0790.1,9.411070e-01,NaN,MA0874.1,9.411070e-01,NaN
73,neg_patterns.pattern_36,68,NaN,NaN,MA0743.2,5.623970e-02,NaN,MA0744.2,5.623970e-02,NaN,MA0122.4,1.586160e-01,NaN
74,neg_patterns.pattern_37,26,NaN,NaN,MA1119.2,1.000000e+00,NaN,MA0105.3,1.000000e+00,NaN,MA2525.1,1.000000e+00,NaN

In [8]:
# Columns to keep 
# pattern - num_seqlets - match0 - qval0 - match1 - qval1 - match2 - qval2

cols_to_keep = ['pattern', 'num_seqlets', 'match0', 'qval0', 'match1', 'qval1', 'match2', 'qval2']
df_clean = df[cols_to_keep]
df_clean

,pattern,num_seqlets,match0,qval0,match1,qval1,match2,qval2
0,pos_patterns.pattern_0,3711,MA0139.2,1.486780e-15,MA1930.2,1.486780e-15,MA1930.1,1.486780e-15
1,pos_patterns.pattern_1,3540,MA0790.1,4.218360e-01,MA0791.1,4.218360e-01,MA0683.1,4.558050e-01
2,pos_patterns.pattern_2,2940,MA0835.3,3.074210e-03,MA1988.2,3.074210e-03,MA2486.1,3.074210e-03
3,pos_patterns.pattern_3,2468,MA0790.1,2.811640e-03,MA0791.1,2.884580e-03,MA0791.2,5.652540e-03
4,pos_patterns.pattern_4,2389,MA1467.2,1.834790e-05,MA1642.1,9.611720e-05,MA1109.1,1.429630e-04
...,...,...,...,...,...,...,...,...
70,neg_patterns.pattern_33,116,MA1499.2,3.040170e-01,MA1639.2,3.040170e-01,MA1504.2,3.040170e-01
71,neg_patterns.pattern_34,81,MA1596.1,8.553260e-02,MA0496.4,8.553260e-02,MA2587.1,8.553260e-02
72,neg_patterns.pattern_35,71,MA1124.1,6.074760e-01,MA0790.1,9.411070e-01,MA0874.1,9.411070e-01
73,neg_patterns.pattern_36,68,MA0743.2,5.623970e-02,MA0744.2,5.623970e-02,MA0122.4,1.586160e-01
74,neg_patterns.pattern_37,26,MA1119.2,1.000000e+00,MA0105.3,1.000000e+00,MA2525.1,1.000000e+00

In [11]:
# Load JASPAR file to generate motif ID to name dictionary 

jaspar_2026="/scratch/prj/stem_cells_pituitary/Georgia/genome/JASPAR_CORE_2026_non-redundant.meme"

# Create a disctionary with key = ID and value = motif name
id_to_motif = {}

# Extract these names from the jaspar file
with open(jaspar_2026, 'r') as file:
    for line in file:
        if line.startswith("MOTIF"):
            parts = line.split()
            # parts[0] is the word MOTIF
            # parts[1] is the ID
            # parts[2] is the Motif name
            if len(parts) >= 3:
                id_to_motif[parts[1]] = parts[2]

print(f'Loaded {len(id_to_motif)} motif names for mapping')

Loaded 2059 motif names for mapping

In [12]:
# Add columns that align with TF motif names 
# New columns called: motif0, motif1, motif2

df_clean['motif0'] = df_clean['match0'].map(id_to_motif)
df_clean['motif1'] = df_clean['match1'].map(id_to_motif)
df_clean['motif2'] = df_clean['match2'].map(id_to_motif)

# Reorder columns
cols_order = ['pattern', 'num_seqlets', 'match0', 'motif0', 'qval0', 'match1', 
              'motif1', 'qval1', 'match2', 'motif2', 'qval2']

df_matched = df_clean[cols_order]
df_matched

/tmp/ipykernel_4021719/1469113142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['motif0'] = df_clean['match0'].map(id_to_motif)
/tmp/ipykernel_4021719/1469113142.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['motif1'] = df_clean['match1'].map(id_to_motif)
/tmp/ipykernel_4021719/1469113142.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['motif2'] = df_clean['match2'].map(id_to_motif)

,pattern,num_seqlets,match0,motif0,qval0,match1,motif1,qval1,match2,motif2,qval2
0,pos_patterns.pattern_0,3711,MA0139.2,CTCF,1.486780e-15,MA1930.2,CTCF,1.486780e-15,MA1930.1,CTCF,1.486780e-15
1,pos_patterns.pattern_1,3540,MA0790.1,POU4F1,4.218360e-01,MA0791.1,POU4F3,4.218360e-01,MA0683.1,POU4F2,4.558050e-01
2,pos_patterns.pattern_2,2940,MA0835.3,BATF3,3.074210e-03,MA1988.2,Atf3,3.074210e-03,MA2486.1,Fosb,3.074210e-03
3,pos_patterns.pattern_3,2468,MA0790.1,POU4F1,2.811640e-03,MA0791.1,POU4F3,2.884580e-03,MA0791.2,POU4F3,5.652540e-03
4,pos_patterns.pattern_4,2389,MA1467.2,Atoh1,1.834790e-05,MA1642.1,NEUROG2,9.611720e-05,MA1109.1,NEUROD1,1.429630e-04
...,...,...,...,...,...,...,...,...,...,...,...
70,neg_patterns.pattern_33,116,MA1499.2,HOXB4,3.040170e-01,MA1639.2,MEIS1,3.040170e-01,MA1504.2,HOXC4,3.040170e-01
71,neg_patterns.pattern_34,81,MA1596.1,ZNF460,8.553260e-02,MA0496.4,MAFK,8.553260e-02,MA2587.1,ZNF672,8.553260e-02
72,neg_patterns.pattern_35,71,MA1124.1,ZNF24,6.074760e-01,MA0790.1,POU4F1,9.411070e-01,MA0874.1,Arx,9.411070e-01
73,neg_patterns.pattern_36,68,MA0743.2,SCRT1,5.623970e-02,MA0744.2,SCRT2,5.623970e-02,MA0122.4,Nkx3-2,1.586160e-01
74,neg_patterns.pattern_37,26,MA1119.2,SIX2,1.000000e+00,MA0105.3,NFKB1,1.000000e+00,MA2525.1,ZNF699,1.000000e+00

In [14]:
# Save as a .csv file
output_csv = '/scratch/prj/stem_cells_pituitary/Georgia/ChromBPnet/outputs/Lactotrophs/tf_modisco/modisco_results_named.csv'
df_matched.to_csv(output_csv, index=False)

## **Iterate through every file**

In [ ]:
# Load JASPAR file to generate motif ID to name dictionary 

jaspar_2026="/scratch/prj/stem_cells_pituitary/Georgia/genome/JASPAR_CORE_2026_non-redundant.meme"

# Create a disctionary with key = ID and value = motif name
id_to_motif = {}

# Extract these names from the jaspar file
with open(jaspar_2026, 'r') as file:
    for line in file:
        if line.startswith("MOTIF"):
            parts = line.split()
            # parts[0] is the word MOTIF
            # parts[1] is the ID
            # parts[2] is the Motif name
            if len(parts) >= 3:
                id_to_motif[parts[1]] = parts[2]

print(f'Loaded {len(id_to_motif)} motif names for mapping')

In [ ]:
# Iterate through the files

cell_types=['Corticotrophs', 'Gonadotrophs', 'Gonadotrophs_Gata2_KO', 'Gonadotrophs_SF1_KO', 
            'Lactotrophs', 'Melanotrophs', 'Somatotrophs', 'Stem_cells', 'Thyrotrophs']

for cell in cell_types:
    
    print(f"Processing: {cell}")
    motif_html= f"/scratch/prj/stem_cells_pituitary/Georgia/ChromBPnet/outputs/{cell}/tf_modisco/modisco_report/motifs.html"

    if not os.path.exists(motif_html):
        print(f"Skipping {cell}: File not found.")
        continue
    
    try:
        table = pd.read_html(motif_html)
        df = table[0]

        cols_to_keep = ['pattern', 'num_seqlets', 'match0', 'qval0', 'match1', 'qval1', 'match2', 'qval2']
        df_clean = df[cols_to_keep]
    
        df_clean['motif0'] = df_clean['match0'].map(id_to_motif)
        df_clean['motif1'] = df_clean['match1'].map(id_to_motif)
        df_clean['motif2'] = df_clean['match2'].map(id_to_motif)

        # Reorder columns
        cols_order = ['pattern', 'num_seqlets', 'match0', 'motif0', 'qval0', 'match1', 
                      'motif1', 'qval1', 'match2', 'motif2', 'qval2']

        df_matched = df_clean[cols_order]

        output_csv = f"/scratch/prj/stem_cells_pituitary/Georgia/ChromBPnet/outputs/{cell}/tf_modisco/modisco_results_named.csv"
        df_matched.to_csv(output_csv, index=False)
    
    except Exception as e:
        print(f"Error processing {cell}: {e}")

print(f"Complete.")

## **Iterate through grouping files**

In [8]:
# Load JASPAR file to generate motif ID to name dictionary 

jaspar_2026="/scratch/prj/stem_cells_pituitary/Georgia/genome/JASPAR_CORE_2026_non-redundant.meme"

# Create a disctionary with key = ID and value = motif name
id_to_motif = {}

# Extract these names from the jaspar file
with open(jaspar_2026, 'r') as file:
    for line in file:
        if line.startswith("MOTIF"):
            parts = line.split()
            # parts[0] is the word MOTIF
            # parts[1] is the ID
            # parts[2] is the Motif name
            if len(parts) >= 3:
                id_to_motif[parts[1]] = parts[2]

print(f'Loaded {len(id_to_motif)} motif names for mapping')

Loaded 2059 motif names for mapping

In [ ]:
# Iterate through the files

cell_types=['Corticotrophs', 'Gonadotrophs', 'Gonadotrophs_Gata2_KO', 'Gonadotrophs_SF1_KO', 
            'Lactotrophs', 'Melanotrophs', 'Somatotrophs', 'Stem_cells', 'Thyrotrophs']
groupings=['grouping_4_down', 'grouping_2_up', 'grouping_2_up', 'grouping_2_up', 
           'grouping_6_up', 'grouping_4_up', 'grouping_7_up', 'grouping_1_up', 'grouping_8_up']
dictionary= dict(zip(cell_types, groupings))

for cell in cell_types:
    
    print(f"Processing: {cell}")
    group=dictionary.get(cell)
    print(f"Group: {group}")
    
    motif_html= f"/scratch/prj/stem_cells_pituitary/Georgia/ChromBPnet/outputs/{cell}/tf_modisco/{group}_modisco_report/motifs.html"

    if not os.path.exists(motif_html):
        print(f"Skipping {cell}: File not found.")
        continue
    
    try:
        table = pd.read_html(motif_html)
        df = table[0]

        cols_to_keep = ['pattern', 'num_seqlets', 'match0', 'qval0', 'match1', 'qval1', 'match2', 'qval2']
        df_clean = df[cols_to_keep]
    
        df_clean['motif0'] = df_clean['match0'].map(id_to_motif)
        df_clean['motif1'] = df_clean['match1'].map(id_to_motif)
        df_clean['motif2'] = df_clean['match2'].map(id_to_motif)

        # Reorder columns
        cols_order = ['pattern', 'num_seqlets', 'match0', 'motif0', 'qval0', 'match1', 
                      'motif1', 'qval1', 'match2', 'motif2', 'qval2']

        df_matched = df_clean[cols_order]

        output_csv = f"/scratch/prj/stem_cells_pituitary/Georgia/ChromBPnet/outputs/{cell}/tf_modisco/{group}_modisco_results_named.csv"
        df_matched.to_csv(output_csv, index=False)
    
    except Exception as e:
        print(f"Error processing {cell}: {e}")

print(f"Complete.")